### ISSUE TITLE
Everything I could figure out and several bugs.

### ISSUE THREAD

**Issue by AndaleTheGreat** [Necr0/ConvenientAdditions#5]
This information was all put together using:
Forge 13.19.1.2188
Convenient Additions 1.0.13-build20
Baubles 1.11-1.4.1 [added because the bauble items didn't seem to work without it]

What I know so far:

The **Seed Box** is pretty much just a dropper. It drops any item transported into it (ie, hopper) at the same speed they are transported into it. It works with redstone the same way a hopper does.
Example: 1 hopper moves items at 4 tick intervals (0.4 sec). So 1 hopper collecting will grab items as they drop out, adding a second to the input makes it so the collecting hopper ends up with a stack sitting on it because it doubles the number dropped from the Seed Box.
It can be used to drop seeds (or seedable plants like potatoes) onto **Compost Soil** which then automatically plants it. (Most of the time.)
This would be useful if you had a mod that auto-plants seeds when dropped on vanilla tilled land or for feeding chickens if they ate floating seeds. (Actually, that would be a good idea. A mod that makes animals able to eat floating, dropped food.)

The **Composter** produces **Dirt Chunks**, 2 kinds of **Compost**, and sometimes **Fertilizer** (I think). Dirt chunks in a 2x2 produce dirt (very handy thing for SkyBlock games). The two types of Compost can be used in 2x2 or 1 Compost + 1 Dirt to create **Compost Soil**.
I cannot see a way to automate it and it holds just a freaking ton of material. I think it takes at least ten wheat for it to produce anything.
BTW, it causes a [crash](http://pastebin.com/KFpz6xai) if you try to use a hopper to insert items. Also, it seems like a missed opportunity to not have it collect items dropped onto it since you have the Seed Box.

**Compost Soil** is (I'm guessing) a better farmland than vanilla. I'm not sure, I have left a vanilla and compost soil farm next to each other and they seem to grow about the same. The only benefit I see is the automation from the dropper but that would be moderately difficult for most players not well versed in redstone. It would be simpler to set up a system with improved redstone/tech mods but at that point there is better automation.
[Sorry, I seem to be nitpicking for this item, didn't mean to. I am just trying to figure out why it is better than vanilla besides the auto planting. Especially since almost every modpack has right-click farming.]

The **Fertilizer** seems to grow any seedling fully or sapling instantly.

The **Detector** & **Player Detector** detect things....... Serisously, I cannot figure out anything about these. The Detector works on players in a globe shape. 

The **Powder Keg** is a neat, but strange choice. It is nearly just TNT, but taken a step further. It is a single stack inventory that will only accept gunpowder (and only thru the packs hopper-like proxies, piping or from hoppers as far as I can figure out). It can be ignited by redstone or fire and the explosion varies in strength and size based on the amount of powder in it. You can break it or use a hopper to retrieve the gunpowder.
The only way I could see this being useful is if adding this mod made gunpowder more dangerous when placed in other storages or made it go bad if left in anything other than the keg. Picking up the Keg with the powder in it would be a big bonus too, but right now it just drops it when broken.

The **Adventurer's Pickaxes** seem like a neat idea but I've yet to use one long enough to matter. They cannot be repaired. The wood simply has no output no matter which or how many of the vanilla logs, planks or sticks you try to fix it with. The [stone](http://pastebin.com/KrFf36BE), [iron](http://pastebin.com/S8s2DRqC), and [diamond](http://pastebin.com/fWefnybM) all cause crashes when attempting to repair and then the items disappear.
A note: I recommend having these set up to call on the textures for the vanilla tool replacements in resource packs rather than making them still be completely vanilla, that is, unless you plan to make them look different from vanilla.

The **Inventory Proxies** work much differently than what I had realized. They "extend" an inventory. Placing either of them with the arrows pointing towards the inventory you wish to extend. This is an improvement over pipes in that the items do no actually move, they seem to be more similar to a "request system" as well which would make it easier to do automation that requires specific amounts of something.
The **Filtered Inventory Proxy** only allows access to the items set into the filter. In the filter you can set up to 3 items and each can have an amount set. - [SCREENSHOT](http://i.imgur.com/Hyc2FY7.png) - I don't know what the amount is supposed to do. I'm pretty sure it is a limiter but the hopper is kinda stuck at 1 every 4 ticks so I can't do anything to prove that with more mods.
In this [screenshot](http://i.imgur.com/h6W2nkH.png) you can see the directions of movement. At the top left is our storage which is extended by the proxies pointing at it, the hoppers attached with a filter above them can only pull the items allowed by the filter, but the hopper on the end is unfiltered and is able to pull any item it can.
This is quite useful for a system using a "dump chest" method to then sort items. The extending of the inventory prevents items from being shoved into a sorting system to cause problems when it has nowhere to go.

The **Set Provider** just confounds me. I feel like I get the idea of what the Set Provider _should_ do but the more I test it the less I seem to be sure about it.

The **Item Transmitter** works much like the Proxies. Place it pointed at an inventory and that inventory can be accessed via the **Item Receiver**. (Not directly, but by a hopper or some other "pull/request" method.)

The Provider and Transmitter are linked by using similar **Channel Modules**.
Note: Shift+Clicking a Color Module into the Set Provider causes a [crash](http://pastebin.com/zDq21Xr7).

The **Platforms** are pretty awesome. These are 1/8 blocks at the top of the block. You cannot see them from below (except by hitbox) and you can jump up thru them. In addition, you can also press shift to drop down thru them. 

The **Sunstone** & **Ring of Light** both are dynamic lights (and pretty hard on the ol' FPS)

The **Tree Tap** can be attached to trees. Attach a **Sap Bottle** to collect sap. Once full you can make either the **Antidote** or a **Bandage**.

The **Slime Arrow** creates an explosion but does not seem to cause damage.
The **Blast Arrow**  does damage but only to mobs/players, not blocks.
The **Creeper Arrow** seems to be the eqiuvalent of a tnt.
Each arrow is set off when it _either_ hits a mob while flying or when a player walks over it. Great way to accidentally kill yourself in a fight.

I read the **Tome of Transmutation** was broken and did not experiment with it.

The **Amulet of Breath** does NOT give you water-breathing, it stops your breath at a single bubble and instead removes charge from the Amulet. Currently it charges faster than it discharges when in use.

The **Ring of Charging** charges the other items from this mod when active. This allows for extended life before recharging of the normal items.

The uses of the **Iron Wrench** are based on the block it is used on.
On the Proxies, Filter and Item Transmitter it rotates the block.
It works as a wrench on most things rotated or dropped by wrenches.
Hover Pads are dropped when shift-right clicked.
On the Set Provider it changes the clicked side's mode to input/output.

No idea/Can't make it work**:**
Leaf Collector
Blazing Rock
Ender Plate
Bandage
The Set Provider. 

Stuff I found confusing**:**
The arrows and dot had me doing everything in reverse.
"Proxy" is a strange choice, but I think "extender" would make it sound like it is accessible by right-click from those points.
The exploding arrows that don't pop until you touch them rather than exploding on impact.
The Set Provider.

**Comment by QbDesu** [comment]
Even if there is a few errors it looks good. Thanks for the bug reports and the documentation. I'll also try to incorporate some of the changes you asked for in the near future. For now I don't have much time and I'll try to follow up on this when I'm back home. I'll also think about changing some of the features that you didn't get without explanation to be more intuitive.

I'll also have to test if some of the features you didn't have any idea about didn't just break. Thanks a lot for helping and I really appreciate what you are doing.

**Comment by QbDesu** [comment]
You'll often see me mention that I will test if something broke. That's because in these cases I'm not sure if it broke or you just didn't figure it out, which of course isn't necessarily a bad thing because it tells me what items could be made more intuitive. I'll probably add short tooltips to a lot of items to give the player a better hint than just the name which as I have to admit is sometimes quite inexpressive or confusing even.

### Seed Box

> It works with redstone the same way a hopper does. Example: 1 hopper moves items at 4 tick intervals (0.4 sec). So 1 hopper collecting will grab items as they drop out, adding a second to the input makes it so the collecting hopper ends up with a stack sitting on it because it doubles the number dropped from the Seed Box.

Don't know what you mean that. It doesn't have redstone controls. Are you describing a dupe bug in the second part? If so I didn't quite get it. >.<

> It can be used to drop seeds (or seedable plants like potatoes) onto Compost Soil which then automatically plants it. (Most of the time.) This would be useful if you had a mod that auto-plants seeds when dropped on vanilla tilled land ...

It's even capable of planting other plants.
❌ It should work with any kind of soil valid for the given plant/seed. I'll test that again.
🐛 Broke for tilled soil in a previous update.
✔️ Fixed in the next version. Caused by farmland's smaller hitbox.

> ...  or for feeding chickens if they ate floating seeds. (Actually, that would be a good idea. A mod that makes animals able to eat floating, dropped food.)  

💡 Good idea I'll try adding it (to the seed box at least) since I was thinking about adding a mod to. I might make it a mod as well as it sounds like it's quite easy to accomplish but that will have to wait until fixed the current bugs of CA.

Features you didn't find (nothing to feel bad about):
* output sides configurable with iron wrench (I know, it doesn't look like it could work.) And it randomly outputs to an output side that is not blocked.
* drops items perfectly straight down
* also makes bone meal, fertilizer and compost be applied automatically

### Composter

> BTW, it causes a crash if you try to use a hopper to insert items.

🐛 Noted! Working on it.
✔️ Fixed in the next version.

> Also, it seems like a missed opportunity to not have it collect items dropped onto it since you have the Seed Box.

💡 I've been thinking about adding just that feature for quite a while now. I just never got around to doing it.
✔️ Implemented. v1.0.15+

> Compost Soil is (I'm guessing) a better farmland than vanilla. I'm not sure, I have left a vanilla and compost soil farm next to each other and they seem to grow about the same. 

It should grow plants significantly faster depending on the degree of degradation. Also it doesn't need a water source to be effective.
✔️ Might be broken. I'll test it.
💡 Works fine. But i may buff it.
✔️ Buffed. v.1.0.14

> [Sorry, I seem to be nitpicking for this item, didn't mean to. I am just trying to figure out why it is better than vanilla besides the auto planting. Especially since almost every modpack has right-click farming.]

It's fine. Feedback is always appreciated. In the Seed Box part I already mentioned it's not supposed to be the only kind of soil the Seed Box works with.

> The Fertilizer seems to grow any seedling fully or sapling instantly.

Pretty much. It's like applying bone meal randomly 2-4 times.

### Proximity Sensor

> The Detector & Player Detector detect things....... Serisously, I cannot figure out anything about these. The Detector works on players in a globe shape.

If you mean the Proximity Sensor. It will be changed one of the next versions. It gives a compartor output depending on the distance to the closest player, the closer the player the stronger the output, 0 at 15 blocks, 15 at 0 blocks(<1 block). I can be powered with redstone to double it's precision at the cost of halving it's range.

### Powder Keg

> It is a single stack inventory that will only accept gunpowder (and only thru the packs hopper-like proxies, piping or from hoppers as far as I can figure out). [...] You can break it or use a hopper to retrieve the gunpowder.

It should be right-clicking with gunpowder to insert it and sneak + right-click to retrieve it.
❌ I'll test it and look into it if it broke.
🐛 Yes, I messed up to code completely last time around.
✔️ Fixed in the next version.

> The only way I could see this being useful is if adding this mod made gunpowder more dangerous when placed in other storages or made it go bad if left in anything other than the keg.

Not gonna happen (in my mod at least). But I may buff it's power maybe. It's meant for mining big caves quickly.

>Picking up the Keg with the powder in it would be a big bonus too, but right now it just drops it when broken.

💡 Good call. I might add that.

### Adventurer's Pickaxe

> The Adventurer's Pickaxes seem like a neat idea but I've yet to use one long enough to matter. They cannot be repaired. The wood simply has no output no matter which or how many of the vanilla logs, planks or sticks you try to fix it with. The stone, iron, and diamond all cause crashes when attempting to repair and then the items disappear.

🐛 Repair recipes broken. Noted! Will try to fix it.
✔️ Fixed both in the next version.

> A note: I recommend having these set up to call on the textures for the vanilla tool replacements in resource packs rather than making them still be completely vanilla, that is, unless you plan to make them look different from vanilla.

Not only the head changes with mining-level-ups. The handle also changes (wood->iron->obsidian) depending on the durability which also rises every level. I'll probably also add a message that tells you what random upgrade you unlock at level-up. For now the [rudimentary wiki-page](https://github.com/Necr0/ConvenientAdditions/wiki/Adventurer's-Pickaxe) can give you an idea of what it's meant to do.

### Inventory Proxies

> The Inventory Proxies work much differently than what I had realized. They "extend" an inventory. Placing either of them with the arrows pointing towards the inventory you wish to extend. This is an improvement over pipes in that the items do no actually move, they seem to be more similar to a "request system" as well which would make it easier to do automation that requires specific amounts of something.

Well, as of now the only thing that can limit stuff to specific amounts is the Set Provider, other than that there's only the vanilla comparator + hoppers madness. 

> The Filtered Inventory Proxy only allows access to the items set into the filter. In the filter you can set up to 3 items and each can have an amount set. - SCREENSHOT - I don't know what the amount is supposed to do. I'm pretty sure it is a limiter but the hopper is kinda stuck at 1 every 4 ticks so I can't do anything to prove that with more mods.

The access to the amount is because the fake slot code is taken from the Set Provider which depends on it. I'll probably write a slot for them to only be about the item and not the amount.

> The arrows and dot had me doing everything in reverse.

💡 I can see why. I might make it more obvious that it's meant to face the inventory it's meant to mimic.

> "Proxy" is a strange choice, but I think "extender" would make it sound like it is accessible by right-click from those points.

Well, to be honest i don't like the sound of extender. Sorry >.< Inventory Interface maybe?

### Set Provider

> The Set Provider just confounds me. I feel like I get the idea of what the Set Provider should do but the more I test it the less I seem to be sure about it.

The Set Provider is quite complicated and I'll hold off on explaining it for now. It's the block I'm most unhappy about in terms of intuitivity.

> Note: Shift+Clicking a Color Module into the Set Provider causes a crash.

🐛 Noted!
✔️ Fixed in the next version. Affected any item not only Color Modules.

### Platforms

> The Platforms are pretty awesome. These are 1/8 blocks at the top of the block. You cannot see them from below (except by hitbox) and you can jump up thru them. In addition, you can also press shift to drop down thru them.

Glad you like them. They were inspired by platforming games that have platforms you can drop down from.

### Sunstone/Ring of Sunlight

> The Sunstone & Ring of Light both are dynamic lights (and pretty hard on the ol' FPS)

💡 I'll try and make them more FPS friendly in the near future.
✔️ It should be way FPS friendlier in the next version.

### Tree Tap

> The Tree Tap can be attached to trees. Attach a Sap Bottle to collect sap. Once full you can make either the Antidote or a Bandage.

Sap can also be used as a sugar supplement for vanilla sugar recipes.

> Each arrow is set off when it either hits a mob while flying or when a player walks over it. Great way to accidentally kill yourself in a fight.

> The exploding arrows that don't pop until you touch them rather than exploding on impact.

💡 The arrows are meant to explode on proximity. But I might make it so only slime arrows do that. I'll also have to add that it also explodes on other living entities' proximity (I forgot about that).
✔️ Changed in the next version. Will work as described above

### Tome of Transmutation

> I read the Tome of Transmutation was broken and did not experiment with it.

💡 The tome itself is not broken. Only the NEI recipe lookup for it is broken. Speaking of which I plan on adding my own recipe lookup to the tome since I don't want the player to have to find them out on their own or look them up online. Like a "?"-button in the top right or similar.
 
### Leaf Collector

Destroys nearby leaves that would usually despawn and spawns their drops on top of the collector. Also dropping apples might double and there is a really small chance for it to turn it into a golden apple.
✔️ I'll check to see if it broke.

### Blazing Rock

I'll probably add a tooltip to make it more obvious.
https://github.com/Necr0/ConvenientAdditions/wiki/Blazing-Rock
❌ I'll check to see if it broke.
🐛 Broken. Using it as funace fuel voids it.
✔️ Fixed in the next version.

### Bandage

✔️ Should be quite obvious so I'll look up if it broke. 
https://github.com/Necr0/ConvenientAdditions/wiki/Bandage

### Ender Plate

I'll add a tooltip: Uses charge to spawn invisible temporary platform blocks around you. It can be recharged by crafting it with ender eyes or by staying near end crystals.
❌ I'll test if it still works.
🐛 Broken.
✔️ Fixed in the next version. Was meant to only be active in the hotbar or offhand. Did the opposite.

**Comment by AndaleTheGreat** [comment]
**Seed Box**
1) The Seed Box seems to be disabled if a redstone signal is applied, but I will double check this.

2) Not a bug. The Box seems to just drop instantly. As fast as I could put into it I can see them come out. The example is because a single hopper can only take in 1 item every 4 ticks, but you can output faster than that from the Seed Box.

**Compost**
Didn't know it didn't need water. Cool. Always a good vanilla farmland replacement.

**Proximity Sensor**
Totally forgot to try comparators. I always forget about those cuz I mastered all my redstone circuitry before they existed. Kinda like how my ability to code is useless because I learned in Basic/QBasic and old as hell HTML & Java.

**Adventurer's Pickaxe**
Didn't know the head changed. Cool. I'd still maybe try to get away from vanilla-identical textures tho. I also assume the recipe will change someday. Adding a seed doesn't seem like much to do for an advanced pick.

**Inventory Proxies**
1) The "request system" comment was because the system does not force items into moving about (causing extra checks from the server to track it) but instead allows things like hoppers to "pull" from the attached inventory.

2) If you went to a 32x texture you could do a bit more detail work on the items to identify how they should face while still keeping the nearly vanilla style. I would also suggest, since they are wooden (or appear to be), maybe making them available in different colors to match the woods used.

3) Interface makes it also sound like it is right-clickable. Proxy still seems better.      ....Item Retrieval System?   No. That becomes the IRS.     
.....nope, I got nothing better. Proxy works so well the more I think about it.

**Platforms**
Only thing I would change is either make a connected texture or expand the current one to the edges or just add an edge touching border. Personally, I love connected textures.
Wait, no, not the only thing. Add a dye to the recipe, make them in several colors. People love to decorate.

**Sunstone/Ring of Sunlight**
I threw OptiFine at it and it was still well above playable, but still a hefty hit compared to my max. Tho, you probably should get some tests from others for that one. I've got a mid-range card on a mid-high pc.

**Tree Tap**
Yeah, I was confused because I blew them up but nothing else seemed to. Makes more sense if it does for all. 

**Tome of Transmutation**
Most things show their list of recipes in JEI by clicking on the progress bar (if one appears). I don't know if this is totally a JEI thing or something modders have to do.

**Leaf Collector**
Ah, not what I expected. Probably not broken. I think the only thing I didn't do was break a tree near it.

A thought tho. What about making these so you put a bunch of them at ground level and ...once the tree is broken... they shear most of the leaves that are directly above them instead of letting them despawn. I mean, leaves fall, but they never accumulate in MC.   Just a thought.   Not sure how it would be useful...... wait, no, you could put all those leaves in the Composter.


**Bandage**
Sat their holding left and right mouse down, furiously shaking my fist at the sky, imagining myself to be some angry man, half naked, holding a bandage, shouting "why you no make blood stop‽"

**Ender Plate**
Ah, I kept trying to run off the edge of things to see if I walked on air and clicking into the distance to check for a teleport..... and, well, a lot of random stuff.

**Comment by QbDesu** [comment]
### Seed Box

1. Shouldn't react to redstone at all. Maybe you accidentally also powered the hopper pointing into it as it conducts redstone signals(strong power) like any other solid block.

2. Correct the Seed Box doesn't even have an inventory. The items inserted will be dropped instantaneously.

### Compost Soil

It worked fine in terms of speeding up growth. Yet, I buffed it slightly to make the impact more significant.

### Proximity Sensors

They'll probably be reworked because i don't like them using comparator outputs.

### Adventurer's Pickaxe

Their texture is not identical but only really similar to vanilla pickaxes. I'll make them more distinguishable in a later update. About 32x32 textures. I might just use them. For now I stuck to 16x16 textures which in some cases had me annoyed by the limitations. I have a few other places in mind that I'll probably change to 32x32. (Item Receiver, Tome of Transmutation, Bandage(making a small roll in 16x16 is hard))

### Inventory Proxies

Inventory Redirector just came into my mind. It makes it's function more apparent and sounds fine to me.

### Platforms

I might add connected textures and/or stretch it to the borders of the block. I'll probably add them along side dyable platforms which are also planned.

### Sunstone/Ring of Sunlight

Yeah, I tried reducing FPS drops the best I could for the next update.

### Launching Arrows

In the next update only slime arrows blow up on proximity and they blow up on all living entities' proximity.

### Tome of Transmutation

I had JEI integration working fine at some point but some API changes broke it. I'll probably rewrite the integration from scratch using the new API since it's not all that much work.

### Leaf Collector

This block is pretty much work in progress hence it doesn't have a recipe. A shearing mode is planned.

### Bandage

I reduced the time needed to apply it from 5 to 3.5 seconds in the next update.

### Composter

There was a bug making it take away all currently held items but only actually insert one of them. 3 pieces of wheat should make it start composting. You can look at the [Convenient Additions default API implementation](https://github.com/Necr0/ConvenientAdditions/blob/1.11/src/main/java/convenientadditions/init/ModCAAPI.java#L49)  to see an overview of the composting masses of each item.

Speaking about the next update, I might release it this night (UTC+1) if not it's gonna happen during the day tomorrow. I have released all of the bugs you reported. These are the current documented changes:

Tweaks:
* sunstone/ring of sunlight: significantly reduced fps drops
* launching arrows: only slime arrows explode on proximity; proximity works on all living entities
* platform: added config option for disabling recipe
* bandage: reduced time needed to apply (5s -> 3.5s)
* compost soil: slight buff
* blazing rock: renamed and retextured to blazing orb
* blazing rock: added tooltip joke + explanation

Fixed Bugs:
* charge items: no longer recharge in water
* adv pick:mining speed depended on stone mined instead of blocks mined
* adv pick:repair recipes cause crash, wooden planks not recognized
* adv pick:ore magnet didn't check if it's unlocked
* composter: crash when piping items in
* composter: bug caused it to take away all items and still only insert 1
* set provider: crash on shift-clicking items
* powder keg: fixed right-click interaction
* seed box: auto-crops: broken with farmland
* blazing rock: voided when used as fuel
* launching arrows: only creeper arrows to be shown in creative menu

**Comment by AndaleTheGreat** [comment]
Seriously, you are the most actively communicative mod author I've come across and super fast about bug fixes. Also quite friendly about all of it. Very impressive all around.

Incidentally, I still cannot figure out the difference in the two proxies. I thought it was some kind of "chaining" function. I figured you could set multiple inventories in a row with these all pointed into the inventories but still attached to each other by being next to each other.       ...That is hard to understand. Let me make a pic.
[Here](http://i.imgur.com/ladxU0T.png) is a pic of what I thought it would do. In this case it actually doesn't even filter, it just pulls from the left-most drawer no matter what I put in the filter.



Have you thought of making the filter make use of redstone based on input levels? [Something like this.](http://i.imgur.com/hulsT0m.png)
It wouldn't help for having three items filtered into one chest (with this setup) but it could be used with other storage mods or for supplying items per need.

Still in old version but noticed the blazing rock will only provide enough heat to cook less than half a cobblestone to smooth stone.



I was bug reporting with Stackie and Survivalist and apparently, somehow, according to the Stackie author it is actually Convenient Additions causing a crash but I'm very surprised. Gonna see if I can make it happen again, but thought I should link it if you wanna read it. [THE THREAD](https://github.com/Lunatrius/Stackie/issues/9#issuecomment-265531794)

**Comment by QbDesu** [comment]
Good call on the proxies. Sided Proxies will be renamed Side-Aware Proxies. The also preserve sidedness. If you access them from a certain side the block they point into will also be accessed from that side. E.g. if you access them from the bottom but the proxy is pointing to the side of the block you can still access the bottom whereas the normal proxies will have you access the side.
The only thing that can combine inventories as of now is the item transmitter/receiver system.
Also still the only thing that can ration items for now is the set provider which will get a slight rework in one of the next versions to make it more intuitive/self-explanatory.

The Blazing Orb as it is called from now on will only give a small amount of burn time but it can be used multiple times in quick succession therefore making the charge it drains match the demand more precisely.

Thanks for reporting the bug. It was caused by the Ore Magnet not checking if the EntityItem has a valid stack. It should be fixed in the next version. [It should be available now!](https://minecraft.curseforge.com/projects/convenient-additions/files/2354922)

**Comment by AndaleTheGreat** [comment]
Oh my god. I finally get the side-aware thing now. Took me reading this 3 times (last night then this morning) before I got it. I was testing with chests and storage drawers, not furnaces and such.

Now [this](http://i.imgur.com/GCNPAw1.png) makes some sense.


I had originally thought that it meant something like [this](http://i.imgur.com/BkPltqR.png) where the "side" proxies would combine into a single arrangement. Tho, now that I understand I see an issue. I can [branch out to multiple outputs](http://i.imgur.com/pyAvuD2.png) which makes for a great sorting system, but I cannot see combine who you could combine them back together so that multiple inventories were on a single line.

**Comment by QbDesu** [comment]
I will add and inventory combiner in the future. Also, to give you a bit of an update since I didn't really communicate within the last week I write this message:

The 1.0.15 update for CA has been released yesterday. Some of the changes were actually suggested or at least somewhat inspired by you and your feedback:
* composter: automatically sucks up items on top of itself
* adventurer's pickaxe: texture rework (now 32x32); broken texture + breaking sound
* added explaining tooltips to a lot of the items
* sided inventory proxy: renamed to side-aware inventory proxy

There's also other notable changes that take care of some problems you previously encountered:
* set provider: small rework to make it more accessible (+performance improvement)
* tome of transmutation: added recipe lookup functionality ("?"-button at the top left corner)

This is as far as the really notable changes go. Because I unfortunately don't have much time under the week because of school and exams I didn't really manage to do as much as I did in last weekend alone. I know I need to transfer a lot of the stuff you wrote to the wiki and don't worry, I will. I really appreciate what you did and I won't just discard what you wrote. Next week winter break starts which means I will have more free time to work on the mod. Also I bought a laptop that should also arrive sometime in the next 2-3 weeks which means I can do some some work while I'm out of house.  

I'd like to give you my todo-list for this winter break so you can see what's coming and that I'm not just doing nothing (I know I have no obligation to justify the things I'm doing or not in my free time but even I would feel bad about myself if I would just goof around lazily):

_I'm gonna check this list as I go so if you care you can look at the progress, if you don't that's also fine of course. Also this list is in no particular order. New features are marked by a 🆕._
- [x] fix Tome of Transmutation JEI integration
- [x] 🆕 seed box: auto animal feeding (as suggested by you)
- [x] 🆕 filtered proxy: blacklist functionality
- [x] 🆕 platforms: rework textures + make dyable 
- [x] 🆕 finish storage matrix block (recipe, texture)
- [x] back-end-only: improve build automation
- [x] back-end-only: clean up third party api references
- [x] proximity sensor: rework (functionality)
- [x] 🆕 powder keg: keep items (as suggested by you)

If I manage to do all that I have a few more ideas but that's it for now.
